web-pr-comment:
  parameters:
    comment:
      description: The comment to add to the PR
      type: string
    maxComments:
      default: 1
      description: Max nb of comments per PR
      type: integer
    pr:
      default: $CIRCLE_PULL_REQUEST
      description: The PR number or URL
      type: string
  steps:
    - run:
        command: sudo apt-get update && sudo apt-get install -y --force-yes ruby-full
        name: Install Ruby
    - run:
        command: |
          curl -sL https://raw.githubusercontent.com/stephencelis/ghi/master/ghi > ghi
          chmod 755 ghi
          sudo mv ghi /usr/local/bin
        name: Install GHI
    - run:
        command: |
          if [[ -z "${GHI_TOKEN}" ]]; then
            echo "GHI_TOKEN not set"
            /bin/false
          fi
        name: Check Token
    - run:
        command: |
          GH_LOGIN=$(curl -sS https://api.github.com/user\?access_token\=$GHI_TOKEN | jq '.login' --raw-output)
          echo "Authenticated with $GH_LOGIN"
          PR_URL=<< parameters.pr >>
          PR_ID=${PR_URL##*/}
          echo "PR_ID=$PR_ID"
          if [ -z $PR_ID ]; then
            echo "No PR found, skipping"
          else
            if [ $(ghi comment --list $PR_ID | grep -c $GH_LOGIN) -ge << parameters.maxComments >> ]; then
              echo "Already commented, skip"
            else
              ghi comment -m "<< parameters.comment >>"  $PR_ID
            fi
          fi
        name: Send Comment
