when: << pipeline.parameters.run-web-job >>
jobs:
  - init

  # Cut a demo if not master
  - build-demo:
      requires:
        - init
      filters:
        branches:
          ignore: /^master$/
  - deploy-demo:
      context: Audius Client
      requires:
        - build-demo
      filters:
        branches:
          ignore: /^master$/

  # Build
  - build-staging:
      requires:
        - init
  - build-production:
      requires:
        - init
      filters:
        branches:
          only: /(^master)|(^hotfix.*)|(^release.*)$/

  - test-staging:
      context: Audius Client
      requires:
        - build-staging

  - deploy-staging-s3:
      context: Audius Client
      requires:
        - build-staging
      filters:
        branches:
          only: /^master$/

  - deploy-staging-cloudflare:
      context: Audius Client
      requires:
        - build-staging
      filters:
        branches:
          only: /^master$/

  - deploy-release-candidate:
      context: Audius Client
      requires:
        - init
        - build-production
      filters:
        branches:
          only: /(^hotfix.*)|(^release.*)$/

  # Allow hotfix to go to staging on command
  - hold-staging:
      type: approval
      requires:
        - init
        - build-staging
      filters:
        branches:
          only: /(^hotfix.*)$/

  - deploy-staging-cloudflare:
      context: Audius Client
      requires:
        - init
        - hold-staging
      filters:
        branches:
          only: /(^hotfix.*)$/

  # Staging IPFS build
  - build-ipfs-staging:
      requires:
        - init
      filters:
        branches:
          only: /^master$/
  - deploy-ipfs-staging:
      context: Audius Client
      requires:
        - build-ipfs-staging
      filters:
        branches:
          only: /^master$/
  - hold-update-staging-ga-ipfs-build:
      type: approval
      requires:
        - deploy-ipfs-staging
      filters:
        branches:
          only: /^master$/
  - update-staging-ga-ipfs-build:
      context:
        - Audius Client
        - Pinata
      requires:
        - hold-update-staging-ga-ipfs-build
      filters:
        branches:
          only: /^master$/
  - publish-staging-build-cids:
      context:
        - Audius Client
      requires:
        - update-staging-ga-ipfs-build
      filters:
        branches:
          only: /^master$/
  - hold-update-ipfs-staging-records:
      type: approval
      requires:
        - update-staging-ga-ipfs-build
      filters:
        branches:
          only: /^master$/
  - update-ipfs-staging-records:
      context:
        - Audius Client
        - Cloudflare API
      requires:
        - hold-update-ipfs-staging-records
      filters:
        branches:
          only: /^master$/

  # Release production web.
  - hold-production:
      type: approval
      requires:
        - build-production
      filters:
        branches:
          only: /(^master)|(^hotfix.*)|(^release.*)$/
  - deploy-production-s3:
      context: Audius Client
      requires:
        - hold-production
      filters:
        branches:
          only: /(^master)|(^hotfix.*)|(^release.*)$/
  - deploy-production-cloudflare:
      context: Audius Client
      requires:
        - hold-production
      filters:
        branches:
          only: /(^master)|(^hotfix.*)|(^release.*)$/

  # Upload sourcemaps
  - deploy-sentry-sourcemaps:
      context: Audius Client
      requires:
        - deploy-production-s3
      filters:
        branches:
          only: /(^master)|(^hotfix.*)|(^release.*)$/

  - publish-github-release:
      context: Audius Client
      requires:
        - hold-production
      filters:
        branches:
          only: /(^master)|(^hotfix.*)|(^release.*)$/

  # Production IPFS build
  - build-ipfs-production:
      requires:
        - init
      filters:
        branches:
          only: /(^release.*)$/
  - deploy-ipfs-production:
      context: Audius Client
      requires:
        - build-ipfs-production
      filters:
        branches:
          only: /(^release.*)$/
  - hold-update-production-ga-ipfs-build:
      type: approval
      requires:
        - deploy-ipfs-production
      filters:
        branches:
          only: /(^release.*)$/
  - update-production-ga-ipfs-build:
      context:
        - Audius Client
        - Pinata
      requires:
        - hold-update-production-ga-ipfs-build
      filters:
        branches:
          only: /(^release.*)$/
  - publish-production-build-cids:
      context:
        - Audius Client
      requires:
        - update-production-ga-ipfs-build
      filters:
        branches:
          only: /(^release.*)$/
  - hold-update-ipfs-production-records:
      type: approval
      requires:
        - update-production-ga-ipfs-build
      filters:
        branches:
          only: /(^release.*)$/
  - update-ipfs-production-records:
      context:
        - Audius Client
        - Cloudflare API
      requires:
        - hold-update-ipfs-production-records
      filters:
        branches:
          only: /(^release.*)$/

  # Distribute staging desktop binaries.
  - hold-dist-mac-staging:
      type: approval
      requires:
        - build-staging
      filters:
        branches:
          only: /(^master)|(^bounce.*)$/
  - dist-mac-staging:
      context: Audius Client
      requires:
        - hold-dist-mac-staging
      filters:
        branches:
          only: /(^master)|(^bounce.*)$/
  - hold-dist-win-staging:
      type: approval
      requires:
        - build-staging
      filters:
        branches:
          only: /(^master)|(^bounce.*)$/
  - dist-win-staging:
      context: Audius Client
      requires:
        - hold-dist-win-staging
      filters:
        branches:
          only: /(^master)|(^bounce.*)$/
  - hold-dist-linux-staging:
      type: approval
      requires:
        - build-staging
      filters:
        branches:
          only: /(^master)|(^bounce.*)$/
  - dist-linux-staging:
      context: Audius Client
      requires:
        - hold-dist-linux-staging
      filters:
        branches:
          only: /(^master)|(^bounce.*)$/

  # Distribute production desktop binaries.
  - hold-dist-mac-production:
      type: approval
      requires:
        - build-production
      filters:
        branches:
          only: /(^master)|(^hotfix.*)|(^release.*)$/
  - dist-mac-production:
      context: Audius Client
      requires:
        - hold-dist-mac-production
      filters:
        branches:
          only: /(^master)|(^hotfix.*)|(^release.*)$/
  - hold-dist-win-production:
      type: approval
      requires:
        - build-production
      filters:
        branches:
          only: /(^master)|(^hotfix.*)|(^release.*)$/
  - dist-win-production:
      context: Audius Client
      requires:
        - hold-dist-win-production
      filters:
        branches:
          only: /(^master)|(^hotfix.*)|(^release.*)$/
  - hold-dist-linux-production:
      type: approval
      requires:
        - build-production
      filters:
        branches:
          only: /(^master)|(^hotfix.*)|(^release.*)$/
  - dist-linux-production:
      context: Audius Client
      requires:
        - hold-dist-linux-production
      filters:
        branches:
          only: /(^master)|(^hotfix.*)|(^release.*)$/
