version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

orbs:
  orb-tools: circleci/orb-tools@10.1.0
  path-filtering: circleci/path-filtering@0.0.2

workflows:
  trigger-workflows:
    jobs:
      - path-filtering/filter:
          pre-steps:
            - checkout
            - orb-tools/pack:
                destination: .circleci/continue_config.yml
                source: .circleci/src
          name: check-updated-files
          mapping: |
            web/.* run-web-workflow true
            mobile/.* run-mobile-workflow true
          base-revision: master
          # this is the path of the configuration we should trigger once
          # path filtering and pipeline parameter value updates are
          # complete.
          config-path: .circleci/continue_config.yml
