version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  swissknife: roopakv/swissknife@0.65.0

jobs:
  trigger-workflows:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - swissknife/run_if_modified:
          base-branch: "master"
          pattern: "^(web).*"
          use-divergence-point: true
          steps-to-run:
            - continuation/continue:
                configuration_path: web/.circleci/config.yml
      - swissknife/run_if_modified:
          base-branch: "master"
          pattern: "^(mobile).*"
          use-divergence-point: true
          steps-to-run:
            - continuation/continue:
                configuration_path: mobile/.circleci/config.yml

workflows:
  trigger-workflows:
    jobs:
      - trigger-workflows
