version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2
  swissknife: roopakv/swissknife@0.65.0

jobs:
  trigger-workflows:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - swissknife/trigger-workflows-for-all-modified:
          base-branch: master
          run-mode-for-base-branch: run_for_last_commit
          code-param-name-map: '
            [
            { "regex": "^(web).*", "param_name": "run_web_workflow" },
            { "regex": "^(mobile).*", "param_name": "run_mobile_workflow" }
            ]'
          additional-param-map: '{"run_trigger_workflow": false}'
          use-divergence-point: true
  trigger-web-workflow:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: web/.circleci/config.yml
          parameters: "{}"
  trigger-mobile-workflow:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: mobile/.circleci/config.yml
          parameters: "{}"

workflows:
  trigger-workflows:
    when: << pipeline.parameters.run_trigger_workflow >>
    jobs:
      - trigger-workflows
  trigger-web-workflow:
    when: << pipeline.parameters.run_web_workflow >>
    jobs:
      - trigger-web-workflow
  trigger-mobile-workflow:
    when: << pipeline.parameters.run_mobile_workflow >>
    jobs:
      - trigger-mobile-workflow

parameters:
  run_web_workflow:
    default: false
    type: boolean
  run_mobile_workflow:
    default: false
    type: boolean
  run_trigger_workflow:
    default: true
    type: boolean
