version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0
  path-filtering: circleci/path-filtering@0.0.2

jobs:
  generate-config:
    docker:
      - image: cimg/base:2021.04

    steps:
      # The circleci cli exposed in the image doesn't support config packing
      # so we install a version that does
      - run:
          name: Install cli
          command: curl -fLSs https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh | DESTDIR=~/cli bash
      - checkout
      - run:
          name: Generate config
          command: ~/cli config pack .circleci/src > .circleci/continue_config.yml
      - persist_to_workspace:
          root: ./
          paths:
            - .circleci/continue_config.yml

workflows:
  trigger-workflows:
    jobs:
      - generate-config
      - path-filtering/filter:
          pre-steps:
            - attach_workspace:
                at: ./
          name: check-updated-files
          mapping: |
            web/.* run-web-workflow true
            mobile/.* run-mobile-workflow true
          base-revision: master
          # this is the path of the configuration we should trigger once
          # path filtering and pipeline parameter value updates are
          # complete.
          config-path: .circleci/continue_config.yml
          filters:
            branches:
              ignore: << pipeline.parameters.branch-regex-to-run-all-workflows-for >>
      - continuation/continue:
          configuration_path: .circleci/continue_config.yml
          parameters: '{
            "run-web-workflow": true,
            "run-mobile-workflow": true
            }'
          filters:
            branches:
              only: << pipeline.parameters.branch-regex-to-run-all-workflows-for >>

parameters:
  # Run all workflows for branches that match this regex
  branch-regex-to-run-all-workflows-for:
    type: string
    default: /(^master)|(^release.*)$/
