version: 2.1

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb in config.yml
parameters:
  run-web-job:
    type: boolean
    default: false
  run-mobile-job:
    type: boolean
    default: false

orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  web:
    executor: continuation/default
    steps:
      - continuation/continue:
          configuration_path: web/.circleci/config.yml
  mobile:
    executor: continuation/default
    steps:
      - continuation/continue:
          configuration_path: mobile/.circleci/config.yml

# our single workflow, that triggers the setup job defined above
workflows:
  web:
    when: << pipeline.parameters.run-web-job >>
    jobs:
      - web
  mobile:
    when: << pipeline.parameters.run-mobile-job >>
    jobs:
      - mobile
